# Generated by Django 4.2.3 on 2023-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_remove_user_is_student_remove_user_is_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('G', 'Guest'), ('T', 'Teacher'), ('S', 'Student')], default='G', max_length=5),
        ),
    ]
