# Generated by Django 4.2.3 on 2023-08-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0004_tprofile_sprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SProfile',
        ),
    ]
