# Generated by Django 4.2.3 on 2023-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0006_sprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='demoprofile.png', upload_to='Profiles/'),
        ),
    ]
